-- Run this in Supabase SQL Editor after deploying the files in public/menu-products.
-- It assigns cleaned product photos to matching menu items and unhides those items.

with image_updates(name, image_url) as (
  values
    ('Nongshim Shin Ramyeon', '/menu-products/nongshim-shin-ramyun.png'),
    ('Nongshim Shin Ramyun', '/menu-products/nongshim-shin-ramyun.png'),
    ('Samyang Kimchi Ramen', '/menu-products/samyang-kimchi-ramen.png'),
    ('Samyang Ramen Kimchi', '/menu-products/samyang-kimchi-ramen.png'),
    ('Paldo Jjajangmen', '/menu-products/paldo-jjajangmen.png'),
    ('Paldo Jjajang Men', '/menu-products/paldo-jjajangmen.png'),
    ('Samyang Tangle Garlic Oil', '/menu-products/samyang-tangle-garlic-oil.png'),
    ('Samyang Tangle Garlic Oil Pasta', '/menu-products/samyang-tangle-garlic-oil.png'),
    ('Samyang Tangle Creamy Mushroom', '/menu-products/samyang-tangle-creamy-mushroom.png'),
    ('Samyang Tangle Creamy Mushroom Pasta', '/menu-products/samyang-tangle-creamy-mushroom.png'),
    ('Paldo Namja Ramyun', '/menu-products/paldo-namja-ramen.png'),
    ('Paldo Namja Ramen', '/menu-products/paldo-namja-ramen.png'),
    ('Paldo Rabokki', '/menu-products/paldo-rabokki.png'),
    ('Paldo Zanmang Loopy', '/menu-products/paldo-zanmang-loopy.png'),
    ('Paldo Zangmyeon Loopy', '/menu-products/paldo-zanmang-loopy.png'),
    ('Bulcha Carbonara', '/menu-products/bulcha-carbonara.png'),
    ('Samyang Buldak Carbonara', '/menu-products/samyang-buldak-carbonara.png'),
    ('Samyang Buldak Carbonara (Halal)', '/menu-products/samyang-buldak-carbonara.png'),
    ('Samyang Carbonara', '/menu-products/samyang-buldak-carbonara.png'),
    ('Samyang Jjajang', '/menu-products/samyang-jjajang.png'),
    ('Samyang Buldak Jjajang', '/menu-products/samyang-jjajang.png'),
    ('Samyang Cream Carbonara', '/menu-products/samyang-cream-carbonara.png'),
    ('Samyang Buldak Cream Carbonara', '/menu-products/samyang-cream-carbonara.png'),
    ('Samyang Buldak Cheese', '/menu-products/samyang-buldak-cheese.png'),
    ('Samyang Buldak Cheese (Halal)', '/menu-products/samyang-buldak-cheese.png'),
    ('Samyang Cheese', '/menu-products/samyang-buldak-cheese.png'),
    ('Samyang Buldak Habanero Lime', '/menu-products/samyang-buldak-habanero-lime.png'),
    ('Samyang Habanero Lime', '/menu-products/samyang-buldak-habanero-lime.png'),
    ('Samyang Buldak Black', '/menu-products/samyang-buldak-black.png'),
    ('Samyang Buldak Black (Halal)', '/menu-products/samyang-buldak-black.png'),
    ('Samyang Black', '/menu-products/samyang-buldak-black.png'),
    ('Samyang Buldak 3x', '/menu-products/samyang-buldak-3x.png'),
    ('Samyang 3x', '/menu-products/samyang-buldak-3x.png'),
    ('Samyang Buldak 2x', '/menu-products/samyang-buldak-2x.png'),
    ('Samyang 2x', '/menu-products/samyang-buldak-2x.png'),
    ('Paldo Kokomen', '/menu-products/paldo-kokomen.png'),
    ('Ottogi Jin Chicken', '/menu-products/otogi-jin-chicken.png'),
    ('Otogi Jin Chicken', '/menu-products/otogi-jin-chicken.png'),
    ('Daebak Ghost Pepper', '/menu-products/40292351-1-daebak-ghost-pepper-dry-black-instant-noodles-with-spicy-chicken-flavour.png'),
    ('Daebak Ghost Pepper Dry Black', '/menu-products/40292351-1-daebak-ghost-pepper-dry-black-instant-noodles-with-spicy-chicken-flavour.png'),
    ('Paldo Volcano Chicken', '/menu-products/paldo-volcano-chicken.png'),
    ('Paldo Volcano Carbonara', '/menu-products/40338886-1-paldo-volcano-carbonara-instant-korean-chicken-noodle.png'),
    ('Keekoo 2x Spicy', '/menu-products/500-korean-raman-keekoo2x-spicy-5-instant-noodles-original-imahgfndz9uv6k7a.png'),
    ('Keekoo Korean Ramen 2x Spicy', '/menu-products/500-korean-raman-keekoo2x-spicy-5-instant-noodles-original-imahgfndz9uv6k7a.png'),
    ('Yopokki Hot & Spicy', '/menu-products/yopokki-hotandspicy.png'),
    ('Yopokki Hot&Spicy', '/menu-products/yopokki-hotandspicy.png'),
    ('Yopokki Hot and Spicy', '/menu-products/yopokki-hotandspicy.png'),
    ('Yopokki Cheese', '/menu-products/yopokki-cheese.png'),
    ('Yopokki Sweet & Spicy', '/menu-products/yopokki-sweet-andspicy.png'),
    ('Yopokki Sweet and Spicy', '/menu-products/yopokki-sweet-andspicy.png'),
    ('Paldo Mr Kimchi', '/menu-products/paldo-mr-kimchi.png'),
    ('Paldo Mr. Kimchi', '/menu-products/paldo-mr-kimchi.png'),
    ('Good Seoul Rapokki Cheesy', '/menu-products/40351583-2-good-seoul-rapokki-cheesy-flavour-korean-ricecake-with-ramen.png'),
    ('Good Seoul Rapokki Cheesy Flavour', '/menu-products/40351583-2-good-seoul-rapokki-cheesy-flavour-korean-ricecake-with-ramen.png'),
    ('Rapokki Cheese', '/menu-products/40351583-2-good-seoul-rapokki-cheesy-flavour-korean-ricecake-with-ramen.png'),
    ('Rapokki Cheesy', '/menu-products/40351583-2-good-seoul-rapokki-cheesy-flavour-korean-ricecake-with-ramen.png'),
    ('Rabokki Cheese', '/menu-products/40351583-2-good-seoul-rapokki-cheesy-flavour-korean-ricecake-with-ramen.png'),
    ('Rabokki Cheesy', '/menu-products/40351583-2-good-seoul-rapokki-cheesy-flavour-korean-ricecake-with-ramen.png'),
    ('Good Seoul Rapokki Spicy', '/menu-products/40351584-2-good-seoul-rapokki-spicy-flavour-korean-ricecake-with-ramen.png'),
    ('Good Seoul Rapokki Spicy Flavour', '/menu-products/40351584-2-good-seoul-rapokki-spicy-flavour-korean-ricecake-with-ramen.png'),
    ('Rapokki Spicy', '/menu-products/40351584-2-good-seoul-rapokki-spicy-flavour-korean-ricecake-with-ramen.png'),
    ('Rabokki Spicy', '/menu-products/40351584-2-good-seoul-rapokki-spicy-flavour-korean-ricecake-with-ramen.png'),
    ('Samyang Original', '/menu-products/samyang-original.png'),
    ('Nongshim Soon Veggie', '/menu-products/nongshim-soon-veggie.png'),
    ('Yopokki Spicy Carbonara', '/menu-products/yopokki-spicy-carbonara.png'),
    ('Paldo Kimchi Jumbo', '/menu-products/paldo-kimchi-jumbo.png'),
    ('Paldo Jumbo Kimchi', '/menu-products/paldo-kimchi-jumbo.png'),
    ('Paldo Seafood Jumbo', '/menu-products/paldo-seafood-jumbo.png'),
    ('Paldo Jumbo Seafood', '/menu-products/paldo-seafood-jumbo.png'),
    ('Paldo Seafood', '/menu-products/paldo-seafood-jumbo.png'),
    ('Broad Noodles Spicy Hot', '/menu-products/whatsapp-image-2026-08-01-at-5-37-47-pm.png'),
    ('Broad Noodle Spicy Hot Flavor', '/menu-products/whatsapp-image-2026-08-01-at-5-37-47-pm.png'),
    ('A-Kuan Broad Noodle Spicy Hot Flavor', '/menu-products/whatsapp-image-2026-08-01-at-5-37-47-pm.png'),
    ('Broad Noodles Spicy Chicken', '/menu-products/broad-noodles-spicy-chicken.png'),
    ('A-Kuan Broad Noodle Spicy Chicken Flavor', '/menu-products/broad-noodles-spicy-chicken.png')
),
updated_items as (
  update public.menu_items item
  set
    image_url = image_updates.image_url,
    status = 'available',
    updated_at = now()
  from image_updates
  where lower(trim(item.name)) = lower(trim(image_updates.name))
  returning item.name, item.image_url
)
select
  count(*) as updated_row_count,
  string_agg(name, ', ' order by name) as updated_items
from updated_items;
